### ISSUE TITLE
Unable to install due to bibtexparser

### ISSUE THREAD

**Issue by lepmik** [adriancaruana/refman#2]
Hi, I wanted to try your app but am unable to install via conda, I tried python 3.11 and 3.8 more info below

`AttributeError: module 'bibtexparser' has no attribute 'bparser'`

````
conda version : 23.5.2
conda-build version : 3.25.0
python versions : 3.11.3, 3.8.18
```

**Comment by adriancaruana** [comment]
Thanks for the issue. It seems to be to the new beta version of bibtexparser, which has a new api. The updated `install.sh` script should handle installing the correct dependencies for you. 

I've been using this repo daily lately, since I'm finishing up my phd thesis -- it's working really well, except there is one issue where `refman` doesn't detect if you create two entries with the same bibtex key. So, just be wary of if you're citing two papers from the same author (or different authors with the same surname) from the same year. You can use the `refman medit` and `refman rm` to fix such issues. 

I'll fix this eventually, but, I'm kinda busy with the thesis 😅 

Let me know how it goes.

**Comment by lepmik** [comment]
Thanks, now it works.

Good luck with the thesis! :)
